### ISSUE TITLE
FAQs page not rendered correctly on Firefox for Android?

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/getglimpse-web#77]
Problem reported here: https://lesbian.solutions/@dragon/103674431287101229

Can someone with an Android phone reproduce this problem? If so, we may need to determine if that's a Firefox problem or a website problem. If it's the latter, we should fix our CSS.

**Comment by dwkretz** [comment]
It looks ok to me on FF 68.5.0

**Comment by TrechNex** [comment]
Okay, we've also had responses from @Member1221 and @chaomodus saying it looks fine.

I'd be interested to know the make & model the OP was using. As @Member1221 was suggesting, it could be they're using a small screened/low resolution device or have increased font size in accessibility settings to the point it breaks the CSS.

Without a screenshot of what they're saying it's hard to tell.

**Comment by BrainBlasted** [comment]
I also cannot reproduce.

**Comment by TrechNex** [comment]
Closing as we can't reproduce the problem.
