### ISSUE TITLE
Ensure SEO

### ISSUE THREAD

**Issue by Member1221** [glimpse-editor/getglimpse-web#9]
It'd be a really good idea to perform some SEO so that we show up in google, duckduckgo, etc. search results.

**Comment by siwalikm** [comment]
@BrainBlasted are you working on this? Otherwise, I can volunteer to pick this up.

**Comment by TrechNex** [comment]
Closing as repository has now moved to https://github.com/glimpse-editor/glimpse-editor.github.io
