### ISSUE TITLE
Any interest in contributors for a better Glimpse website?

### ISSUE THREAD

**Issue by joniler** [glimpse-editor/getglimpse-web#90]
COPYPASTA of issue #387 on the main Glimpse repo:

I feel that the new website isn't a great representation of the new direction of the project. The website should be updated to look good and give people a good impression of the new redesign and etc.

Are you guys interested in contributors for that? I am a frontend web developer and would be interested in contributing to that.

I couldn't find anywhere else to send this/post this, so I figured an issue on Github was the best way to go.

Cheers!

@BrainBlasted let me know if you would be down with this! :)

**Comment by BrainBlasted** [comment]
I would indeed :) I'm not the best at web design and lately haven't had the time to improve it as I would have liked.

**Comment by joniler** [comment]
Sorry for taking forever to get back to you, would still like to work on this. Stuff got nuts at work with the COVID junk. Maybe I can just kinda start jamming on one reusing some of the existing content, then I can hit you up once I have something going?

**Comment by TrechNex** [comment]
Closing as repository has now moved to https://github.com/glimpse-editor/glimpse-editor.github.io
